name: First Workflow

#trigger the workflow to run
#manually trigger the workflow
on: workflow_dispatch
# work to be done
jobs:
  first-job:
    # now for the first job we need to define runner/environment that our job will execute on.
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world!"
      - name: print goodbye
        run: echo "done - bye!"
